### ISSUE TITLE
Opravit IOREF u tlačítek, potenciometrů, světelného senzoru, DHT11, ...

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/ArduinoLearningKitStarter#11]
Je potřeba nahradit dráhy +5V za IOREF u pull-upů na tlačítka, u potenciometrů, světelného senzoru, na napájení DHT11 a je otázka co s pinheady J6 (UART/SERIAL) a J7 (analogové senzory). @cednik @yaqwsx 

DHT11: [Spotřeba (str. 3)](https://www.gme.cz/data/attachments/dsh.772-137.2.pdf) čipu by měla být v desítkách miliampér a [napájecí napětí](https://www.gme.cz/data/attachments/dsh.772-137.1.pdf) od 3,3 (délka kabelu do 20 cm) do 5,5 V.

Aktuálně jsou totiž kity nekompatibilní s 3,3V procesory (ESP, ARM) a hrozí i jejich zničení.

**Comment by yaqwsx** [comment]
#12 řeší.
