### ISSUE TITLE
Opravit polohu a počet montážních otvorů

### ISSUE THREAD

**Issue by yaqwsx** [RoboticsBrno/ArduinoLearningKitStarter#13]

**Comment by cleveHEX** [comment]
Jak by se to mělo provést?

**Comment by JarekParal** [comment]
@yaqwsx Nepamatuješ si, co přesně jsme chtěli upravit?

Přidat další díry v centimetrovém rastru?

**Comment by yaqwsx** [comment]
Chceme 4 díry ve všech rozích. Chceme kulaté rohy.

**Comment by JarekParal** [comment]
Takže nechat 3 díry pro Arduina Uno a přidat další 4 díry v centimetrovém rastru do všech rohů (+ zaoblené rohy)?

**Comment by yaqwsx** [comment]
Huh? My nejsme montážními odtvory kompatibilní s Arduino Uno. Takže bych nechal jenom 4 otvory v rozích.

**Comment by JarekParal** [comment]
Já myslel, že ty aktuální tři montážní otvory jsou právě Uno kompatibilní.

**Comment by yaqwsx** [comment]
Vůbec, jsou na prasáka tam, kde bylo místo.

Honza


Dne 20.10.2018 v 20:38 Jaroslav Páral napsal(a):

**Comment by JarekParal** [comment]
Finální řešení:
Součásné otvory odstranit a přidat 4 otvory, které budou odpovídat Arduino otvorům. 
Přidat další 4 otvory do rohů DPS v milimetrovém/centimetrovém rastru.

**Comment by JarekParal** [comment]
992ecb5a27466dadcc3b4492c06f01643f53f38f
