### ISSUE TITLE
Doladit kompatibilitu Arduino - ESP32

### ISSUE THREAD

**Issue by yaqwsx** [RoboticsBrno/ArduinoLearningKitStarter#19]
Problémové je zejména I2C a SPI. Preferuji řešit na úrovni HW (ať je to blbuvzdornější) - tzn. defaultní piny na ESP32 (specifikované Arduino frameworkem) mapují na odpovídající piny na Arudinu.

Deska musí být použitelná jako redukce ESP32 < = > Arduino Nano < = > Arduino Uno

**Comment by cleveHEX** [comment]
Navrhuji uzavřít, protože je to záležitost knihovny a tam tato issue je.

**Comment by JarekParal** [comment]
Řeší se v rámci issue v ALKS knihovně: https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/issues/5
