### ISSUE TITLE
Změna názvu knihovny pro ALKS

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/ArduinoLearningKitStarter#25]
Přejmenovat knihovnu LearningKit.h na ALKS.h (případně udělat ALKS.h jen jako include Learning.h). Děti mi v tom názvu dělají dost často chybu a nesedí to s názvem DPS.

Možná spíš issue do: https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library

**Comment by cleveHEX** [comment]
Zavřít, v mé verzi implementováno.

**Comment by JarekParal** [comment]
Pošli pull-request

**Comment by cleveHEX** [comment]
Hotovo.
