### ISSUE TITLE
Repozitář je příliš těžkopádný

### ISSUE THREAD

**Issue by cleveHEX** [RoboticsBrno/ArduinoLearningKitStarter#35]
- [x] Přesunout branch wiki do zvláštního repozitáře.
- [ ] Odstranit PDF schéma a přesunout ho do releases?

**Comment by JarekParal** [comment]
Jaké je tedy finální řešení?

Za mě jsou v zásadě jen dvě možnosti, co dělat s dokumentačníma fotkami a dalšími materiály (schémat, BOM, výkresy, ...):
- vše držet jako součást repozitáře
- přesunout tyto soubory do releasů

## Výhody a nevýhody 

### Vše držet jako součást repozitáře

\+ všechny data jsou pohromadě
\+ dostupné i offline
\+ vhodnější pro případné generování webových stránek z dokumentace
\- zvětšuje se velikost repozitáře => repozitáře můžou dost bobtnat
\- pokud někdo nahraje velký soubor (např. zapomene zmenšit fotky), tak se repozitář rozroste o mnoho MB 
\? jak řešit soubory ze starších verzí při přidávání nových

### Přesunout tyto soubory do releasů

\+ nebobtnal by repozitář
\+ soubory jsou jednoznačně spojené s releasem – fotky patří k dané verzi DPS atd.
\- soubory v releasu žijí separátně od repozitáře
\- uživatel musí umět pracovat s další částí GitHubu

## Další otázky

Jak synchronizovat releasy s kompletní dokumentací?

## Výsledek

Já bych asi s menší převahou preferoval první možnost, ačkoliv v tomto repozitáři jsou aktuálně použity obě dvě varianty.

Co na to @CornyjK @yaqwsx  @Tasssadar @dzarda @cednik @bsaid?
