### ISSUE TITLE
Arduino library manager 

### ISSUE THREAD

**Issue by TomasRoj** [RoboticsBrno/ArduinoLearningKitStarter#38]
Čau,

Narazil jsem tady na vás repo a líbí se mi ten nápad! Chci se zeptat jestli je knihovna dostupná na arduino library manager. Pokud ne můžu obstarat :wink:

**Comment by TomasRoj** [comment]
Případně ještě přidat nějaké příklady

**Comment by JarekParal** [comment]
Ahoj,

pokud myslíš [ArduinoLearningKitStarter-library](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library), tedy knihovnu k výukové desce ALKS, tak ta je v Arduino Library Manageru dostupná: 
![image](https://user-images.githubusercontent.com/6726556/56147648-f91bbd80-5fa8-11e9-8b9b-f745f755b339.png)

Pokud budeš mít ale chuť, tak určitě uvítáme PR do [README.md](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/blob/master/README.md)  s touto informací.

Co se týče příkladů, tak máme 3 základní [v repozitáři](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/tree/master/examples) a taktéž uvítáme PR s dalšími :-).

**Comment by bsaid** [comment]
Ahoj, za vytvoření příkladů budeme jenom rádi.

**Comment by TomasRoj** [comment]
Ok, teď jdu na to. Jsem rád pokud mohu pomoci arduino komunitě 🔥👌

**Comment by TomasRoj** [comment]
jo a ještě. Na jekém pinu na shieldu je bzučák?

**Comment by JarekParal** [comment]
https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/blob/9704050753575767df3dff789c11dc6c3e122450/README.md#piezo
